### ISSUE TITLE
issue 6 for Milestone 3: Training the model

### ISSUE THREAD

**Issue by AnnKigera** [AnnKigera/BI2PROJECT#6]
- [ ] Data Splitting
- [ ] Bootstraping
- [ ] Cross Validation (basic, repeated, or LOOCV)
- [ ] Model training for either classification, regression, association or clustering (as applicable)
- [ ] Model performance comparison using resamples(for classification and regression)
